AWSTemplateFormatVersion: '2010-09-09'
Description: Blue ASG

Resources:
  LaunchTemplateBlue:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: BlueTemplate
      LaunchTemplateData:
        ImageId: ami-0c02fb55956c7d316
        InstanceType: t2.micro
        KeyName: devops
        SecurityGroupIds:
          - !ImportValue BlueGreenEC2SecurityGroup
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            yum install -y httpd
            systemctl start httpd
            systemctl enable httpd
            echo "<h1>Blue ASG</h1>" > /var/www/html/index.html

  AutoScalingGroupBlue:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !ImportValue BlueGreenSubnet1
        - !ImportValue BlueGreenSubnet2
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplateBlue
        Version: !GetAtt LaunchTemplateBlue.LatestVersionNumber
      MinSize: 1
      MaxSize: 2
      DesiredCapacity: 1
      TargetGroupARNs:
        - !ImportValue BlueGreenTargetGroupBlue
      Tags:
        - Key: Name
          Value: BlueGreen-ASG-Blue
          PropagateAtLaunch: true

Outputs:
  LaunchTemplateBlueId:
    Value: !Ref LaunchTemplateBlue
    Export:
      Name: BlueGreenLaunchTemplateBlue

  AutoScalingGroupBlueName:
    Value: !Ref AutoScalingGroupBlue
    Export:
      Name: BlueGreenASGBlue
