AWSTemplateFormatVersion: '2010-09-09'
Description: Green ASG

Resources:
  LaunchTemplateGreen:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: GreenTemplate
      LaunchTemplateData:
        ImageId: ami-0c02fb55956c7d316
        InstanceType: t2.micro
        KeyName: devops
        SecurityGroupIds:
          - !ImportValue BlueGreenEC2SecurityGroup
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            yum install -y httpd
            systemctl start httpd
            systemctl enable httpd
            echo "<h1>Green ASG</h1>" > /var/www/html/index.html

  AutoScalingGroupGreen:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !ImportValue BlueGreenSubnet1
        - !ImportValue BlueGreenSubnet2
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplateGreen
        Version: !GetAtt LaunchTemplateGreen.LatestVersionNumber
      MinSize: 1
      MaxSize: 2
      DesiredCapacity: 1
      TargetGroupARNs:
        - !ImportValue BlueGreenTargetGroupGreen
      Tags:
        - Key: Name
          Value: BlueGreen-ASG-Green
          PropagateAtLaunch: true

Outputs:
  LaunchTemplateGreenId:
    Value: !Ref LaunchTemplateGreen
    Export:
      Name: BlueGreenLaunchTemplateGreen

  AutoScalingGroupGreenName:
    Value: !Ref AutoScalingGroupGreen
    Export:
      Name: BlueGreenASGGreen
