AWSTemplateFormatVersion: '2010-09-09'
Description: Security groups for ALB and EC2

Resources:
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ALB Access
      VpcId: !ImportValue BlueGreenVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: BlueGreenALBSecurityGroup

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP from ALB
      VpcId: !ImportValue BlueGreenVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref ALBSecurityGroup
      Tags:
        - Key: Name
          Value: BlueGreenEC2SecurityGroup

Outputs:
  BlueGreenALBSecurityGroup:
    Value: !Ref ALBSecurityGroup
    Export:
      Name: BlueGreenALBSecurityGroup

  BlueGreenEC2SecurityGroup:
    Value: !Ref EC2SecurityGroup
    Export:
      Name: BlueGreenEC2SecurityGroup
