INSERT INTO EXCHANGE_VALUE(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE)
VALUES (10001, 'USD', 'INR', 74.85);
INSERT INTO EXCHANGE_VALUE(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE)
VALUES (10002, 'EUR', 'INR', 88.00);
INSERT INTO EXCHANGE_VALUE(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE)
VALUES (10003, 'AUD', 'INR', 54.12);
