apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-exchange-qa
  labels:
    app: currency-exchange
spec:
  replicas: 2
  selector:
    matchLabels:
      app: currency-exchange
  template:
    metadata:
      labels:
        app: currency-exchange
    spec:
      containers:
      - name: currency-exchange-app
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: currency-exchange-qa-service
spec:
  selector:
    app: currency-exchange
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer
